trigger: none
name: 'VNet'

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: 'AzureTest'
  DeploymentDefaultLocation: 'westeurope'
  ResourceGroupName: 'acr-rg'

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      connectedServiceName: 'AzureTest'
      ResourceGroupName: $(ResourceGroupName)
      location: $(DeploymentDefaultLocation)
      csmFile: deploy/vnet.bicep
      csmParametersFile: deploy/parameters/vnet.parameters.json