trigger: none
name: 'ResourceGroup'

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: 'AzureConnection'
  DeploymentDefaultLocation: 'westeurope'
  ResourceGroupName: 'CARML-ado-rg'

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      connectedServiceName: $(ServiceConnectionName)
      ResourceGroupName: $(ResourceGroupName)
      location: $(DeploymentDefaultLocation)
      csmFileLink: deploy/vnet.bicep
      csmParametersFile: deploy/parameters/vnet.parameters.json