trigger: none
name: 'ResourceGroup'

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: 'AzureConnection'
  DeploymentDefaultLocation: 'westeurope'
  ResourceGroupName: 'CARML-ado-rg'

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      location: $(DeploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: deploy/rg.bicep