trigger: none
name: 'VNet'

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: 'AzureConnection'
  DeploymentDefaultLocation: 'westeurope'
  ResourceGroupName: 'acr-rg'

jobs:
- job:
  steps:
  # - task: AzureResourceManagerTemplateDeployment@3
  #   inputs:
  #     deploymentScope: 'Resource Group'
  #     connectedServiceName: 'AzureTest'
  #     ResourceGroupName: $(ResourceGroupName)
  #     location: $(DeploymentDefaultLocation)
  #     csmFile: deploy/vnet.bicep
  #     csmParametersFile: deploy/parameters/vnet.parameters.json

    - task: AzureCLI@2
      displayName: 'deploy a Bicep file from Azure CLI'
      inputs:
        addSpnToEnvironment: true
        azureSubscription: '$(azureSubscription)'
        connectedServiceNameARM: '$(ServiceConnectionName)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          # Log into Az-PowerShell context
          # . $profile # Load PS-Profile configuration
          $SecuredPassword = ConvertTo-SecureString -AsPlainText -String $env:servicePrincipalKey
          $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $env:servicePrincipalId, $SecuredPassword
          $null = Connect-AzAccount -ServicePrincipal -TenantId $env:tenantId -Credential $Credential
          # Deploy Bicep file
          az deployment group create --resource-group $(ResourceGroupName) --template-file deploy/vnet.bicep --parameters deploy/parameters/vnet.parameters.json


      