name: CARML Workload Deploy - RG

on:
  workflow_dispatch:
  # inputs:
  #   location:
  #     description: "location"
  #     required: true
  #     type: string
  push:
    branches:
      - main
    paths: # Only run when these paths change
      - "deploy/parameters/rg**" # trigger on any change in the deploy/parameters folder
      - "deploy/rg.bicep" # trigger on a change in the rg.bicep file

permissions:
  id-token: write
  contents: read

env:
  LOCATION: westeurope
  MODULE_FILE_PATH: deploy/rg.bicep
  PARAMETERS_FILE_PATH: deploy/parameters/rg.parameters.json

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v3.3.0
      - name: Run Bicep linter
        run: az bicep build --file ${{ env.MODULE_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/arm-deploy@v1
        name: Deploy workload
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: subscription
          # region: ${{ inputs.location }} # Uncomment this line and comment the next line to use the input parameter
          region: ${{ env.LOCATION }}
          template: ${{ env.MODULE_FILE_PATH }}
          parameters: ${{ env.PARAMETERS_FILE_PATH }}
