name: CARML Workload Deploy - VNet
concurrency: carml-deploy # Only allow one instance of this workflow to run at a time

on:
  workflow_dispatch:
  # inputs:
  #   location:
  #     description: "location"
  #     required: true
  #     type: string
  push:
    branches:
      - main
    paths: # Only run when these paths change
      - "deploy/parameters/vnet**" # trigger on any change in the deploy folder

permissions:
  id-token: write
  contents: read

env:
  MODULE_FILE_PATH: deploy/vnet.bicep
  PARAMETERS_FILE_PATH: deploy/parameters/vnet.parameters.json
  RESOURCE_GROUP_NAME: CARML-test-rg

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: azure/login@v1
  #       name: Sign in to Azure
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     - uses: actions/checkout@v3.3.0
  #     - name: Run Bicep linter
  #       run: az bicep build --file ${{ env.MODULE_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    # needs: [lint]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/arm-deploy@v1
        name: Deploy CARML workload
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ${{ env.MODULE_FILE_PATH }}
          parameters: ${{ env.PARAMETERS_FILE_PATH }}
